---
- hosts: all
  become: true
  tasks: 
    - name: Install Apache and PHP
      package:
        update_cache: yes
        name: "{{ packages }}"
        state: latest
      loop: "{{ packages.split(',') }}"
    - name: Start Apache on CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'CentOS'